title: Durga Ram Prasad Meesala
logo: /assets/img/headshot_circle.png
description: Data Engineer | Data Analyst | Python & SQL Expert | ETL Pipelines & Data Warehousing | Cloud Solutions (AWS, Azure, GCP) | Machine Learning & Predictive Analytics | Tableau & Power BI Visualization
show_downloads: False
theme: jekyll-theme-minimal
